name:                servant-auth-firebase
version:             0.1.0.0
license:             BSD3
author:              Tommy Engström
maintainer:          tommy@tommyengstrom.com

category:            Web

dependencies:
- base >= 4.7 && < 5

language:  GHC2021
default-extensions:
- BlockArguments
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- EmptyCase
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- RankNTypes
- StrictData
- TupleSections
- TypeFamilies
- ViewPatterns

ghc-options:
- -Weverything
- -Werror
- -Wno-all-missed-specialisations
- -Wno-implicit-prelude
- -Wno-missing-export-lists
- -Wno-missing-import-lists
- -Wno-missing-local-signatures
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-safe
- -Wno-unsafe
- -Wno-missing-kind-signatures
- -Wno-missing-poly-kind-signatures
- -Wno-monomorphism-restriction
- -Wno-missing-role-annotations

library:
  source-dirs: src
  dependencies:
  - bytestring
  - firebase-jwk
  - http-types
  - servant
  - aeson
  - containers
  - servant-server
  - servant-client
  - servant-client-core
  - servant-auth-server
  - openapi3
  - servant-openapi3
  - insert-ordered-containers
  - text
  - microlens
  - wai
  - mtl
  - jose
  - rio
  - http-client-tls
  - generic-lens
  - monad-time
tests:
  servant-auth-firebase-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-auth-firebase
    - hspec
    - servant-server
    - warp
    - time
    - text
    - bytestring
    - mtl
    - monad-time
