name:                servant-auth-firebase
version:             0.1.0.0
license:             BSD3
author:              Tommy Engström
maintainer:          tommy@tommyengstrom.com

category:            Web

dependencies:
- base >= 4.7 && < 5
- bytestring
- firebase-jwk
- http-types
- servant
- servant-server
- text
- wai
- time
- warp
- mtl
- jose
- monad-time

default-extensions:
      ImportQualifiedPost
      InstanceSigs
      DataKinds
      DefaultSignatures
      DeriveAnyClass
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveTraversable
      DerivingStrategies
      DerivingVia
      DuplicateRecordFields
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      GeneralizedNewtypeDeriving
      LambdaCase
      MultiParamTypeClasses
      NoImplicitPrelude
      NamedFieldPuns
      OverloadedLabels
      OverloadedStrings
      RankNTypes
      ScopedTypeVariables
      StandaloneDeriving
      TupleSections
      TypeApplications
      TypeFamilies
      TypeOperators
      ViewPatterns
ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wincomplete-record-updates
- -Wincomplete-patterns

library:
  source-dirs: src

tests:
  servant-auth-firebase-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-auth-firebase
    - hspec
